name = "CarloAnalysis"
uuid = "074ae576-0ee5-4533-b44a-9466da945657"
authors = ["PatXue <95881915+PatXue@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
